name: Formatting

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  shell-format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install shfmt
        run: sudo apt-get update && sudo apt-get install -y shfmt

      - name: Validate shell formatting
        run: shfmt -d .

  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install prettier
        run: npm install --global prettier

      - name: Validate formatting
        run: prettier --check "**/*.{md,yml,yaml,json,jsonc,css}"
